language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - sudo chown -R $USER $(brew --repo)
  - git -C $(brew --repo) reset --hard origin/master
  - git -C $(brew --repo) clean -qxdff
  - mkdir -p $(brew --repo)/Library/Taps/kaos
  - ln -s $PWD $(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}
  - cd $(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/${TRAVIS_REPO_SLUG}"
  - env | grep TRAVIS_

script:
  - brew audit --strict

notifications:
  email:
    on_success: never
    on_failure: always
